### PR TITLE
chore: Update 111624-sprint-1-review.md

### PR DESCRIPTION
**Pull request by jet0612**

### CODE REVIEW

**Comment by Shyam-Sundar-Bharathi** [comment]
I updated "Chore" in the title to "chore" per defined linting.

**Review by Shyam-Sundar-Bharathi — APPROVED** [review]
"Attended by" section has been added based on Dylan's suggestion. I'm approving.

**Review by shouhardik — APPROVED** [review]
Verified the changes, hence approving

**Comment by MitchelHsu** [comment]
@jet0612 just a few questions:
- Can you please use the "Reviewers" instead of "Assignees" to assign the reviewers for this PR?
- I think we should name our branch according to the issue

**Pull request merged**
